#! /bin/bash

echo "BEGIN OF PREPARE-COMMIT-MSG-HOOK"
echo "Arguments passed to prepare-commit-msg hook:"
echo "commit log message filename: $1"
echo "source of commit message: $2"
#echo "commit message: $(cat $1)"
echo "END OF PREPARE-COMMIT-MSG-HOOK"